# Generated by Django 4.2.25 on 2025-10-12 14:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(default=datetime.date(2025, 10, 12))),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "price_per_person",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="places.place",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["place", "date"], name="idx_visit_place_date"),
                    models.Index(
                        fields=["place", "created_at"], name="idx_visit_place_created"
                    ),
                ],
            },
        ),
    ]
