# Generated by Django 4.2.25 on 2025-10-12 15:10

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foods",
                        to="accounts.household",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitFood",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "price_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_foods",
                        to="foods.food",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_foods",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["food"], name="idx_visitfood_food"),
                    models.Index(fields=["visit"], name="idx_visitfood_visit"),
                    models.Index(fields=["created_at"], name="idx_visitfood_created"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(
                django.db.models.functions.text.Lower("name"),
                name="idx_food_lower_name",
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(fields=["household"], name="idx_food_household"),
        ),
        migrations.AddConstraint(
            model_name="food",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("household"),
                name="uniq_food_household_lower_name",
            ),
        ),
    ]
