# Generated by Django 4.2.25 on 2025-10-12 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("categorization", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "price_range",
                    models.CharField(
                        choices=[
                            ("€", "€"),
                            ("€€", "€€"),
                            ("€€€", "€€€"),
                            ("€€€€", "€€€€"),
                            ("€€€€€", "€€€€€"),
                        ],
                        default="€",
                        max_length=5,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                (
                    "avg_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "avg_price_pp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("visits_count", models.PositiveIntegerField(default=0)),
                ("last_visit_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="places",
                        to="locations.area",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="places",
                        to="accounts.household",
                    ),
                ),
                (
                    "place_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="places",
                        to="categorization.placetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaceTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="places.place"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categorization.tag",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="place",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="places",
                through="places.PlaceTag",
                to="categorization.tag",
            ),
        ),
        migrations.AddIndex(
            model_name="placetag",
            index=models.Index(fields=["tag", "place"], name="idx_placetag_tag_place"),
        ),
        migrations.AlterUniqueTogether(
            name="placetag",
            unique_together={("place", "tag")},
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["household", "place_type"], name="idx_place_household_type"
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["area", "price_range"], name="idx_place_area_pricerange"
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("household"),
                models.F("area"),
                name="uniq_place_household_area_lower_name",
            ),
        ),
    ]
