# Generated by Django 4.2.25 on 2025-10-12 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_types",
                        to="accounts.household",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="accounts.household",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("name"),
                        name="idx_tag_lower_name",
                    ),
                    models.Index(fields=["household"], name="idx_tag_household"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("household"),
                name="uniq_tag_household_lower_name",
            ),
        ),
        migrations.AddIndex(
            model_name="placetype",
            index=models.Index(
                django.db.models.functions.text.Lower("name"),
                name="idx_placetype_lower_name",
            ),
        ),
        migrations.AddIndex(
            model_name="placetype",
            index=models.Index(
                fields=["household", "is_active"], name="idx_placetype_household_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="placetype",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("household__isnull", True)),
                name="uniq_global_placetype_lower_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="placetype",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("household"),
                condition=models.Q(("household__isnull", False)),
                name="uniq_local_placetype_household_lower_name",
            ),
        ),
    ]
