# Generated by Django 4.2.25 on 2025-10-12 14:17

from django.db import migrations, models
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("name"),
                        name="idx_area_lower_name",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="uniq_area_lower_name_global",
            ),
        ),
    ]
